### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by jdecock** [alphgal/charles-dickens_dombey-and-son#1]
se modernize-spelling (remember to include an [Editorial] tag on the commit)
- [ ] "a-waiting" should be changed to "awaiting" (chapter-44.xhtml)
- [ ] "by the bye" should be changed to "by the by" (chapter-31.xhtml, chapter-32.xhtml, chapter-48.xhtml)
- [ ] "de-vilish" should be changed to "devilish" (chapter-7.xhtml, chapter-10.xhtml, chapter-20.xhtml, chapter-21.xhtml, chapter-26.xhtml, chapter-40.xhtml)
- [ ] "intrust" should be changed to "entrust" (chapter-49.xhtml)
- [ ] "shew" should be changed to "show" (chapter-12.xhtml)

se find-mismatched-dashes (remember to include an [Editorial] tag on the commit)
- [ ] "cat-like" should be changed to "catlike" (chapter-17.xhtml, chapter-46.xhtml)

Chapter titles
- [ ] You don't need to keep the chapter label in your chapter titles ([SEMOS 8.1.4](https://standardebooks.org/manual/1.6.4/8-typography#8.1.4)). For example, the Chapter 1 title should be changed to:
```
<header>
	<h2 epub:type="ordinal z3998:roman">I</h2>
	<p epub:type="bridgehead">Dombey and Son.</p>
</header>
```

dedication.xhtml
- [ ] Remove `role="doc-dedication"`

preface-1.xhtml and preface-2.xhtml
- [ ] These aren't letters and shouldn't be styled as such. Remove the `<blockquote>` and `epub:type="se:letter.dateline"`. You'll also need to change `[epub|type~="z3998:letter"] footer` to `footer` in local.css.
- [ ] The `<time>` tag isn't properly formatted. `datetime` has to be exactly 10 characters long: yyyy-mm-dd.

chapter-7.xhtml
- [ ] You need to add `class="eoc"` to `<abbr>` tags when the final period in it also ends the sentence ([SEMOS 8.10.3](https://standardebooks.org/manual/1.6.4/8-typography#8.10.3)). _He’s tough, ma’am, tough, is <abbr epub:type="z3998:personal-name">J. B.</abbr> Tough, and de-vilish sly!_

chapter-11.xhtml
- [ ] There's a period that needs to be moved inside quotation marks: _My opinion is ‘keep ’em at it’.”_ to _My opinion is ‘keep ’em at it.’<HAIR_SPACE>”_

chapter-14.xhtml
- [ ] The `<blockquote>` should be epub:type="z3998:verse" because it's a poem fragment ([SEMOS 7.5.6.1.2](https://standardebooks.org/manual/1.6.4/8-typography#7.5.6.1.2)).

chapter-15.xhtml
- [ ] The `<blockquote>` should be epub:type="z3998:song" ([SEMOS 7.5.6.1.3](https://standardebooks.org/manual/1.6.4/8-typography#7.5.6.1.3)). Between this change and the one for chapter-14.xhtml, you will also need to remove the `[epub|type~="z3998:poem"]` selectors in local.css and add the selectors for `[epub|type~="z3998:verse"]` and `[epub|type~="z3998:song"]`.

chapter-26.xhtml
- [ ] Josh isn't an abbreviation: _"<abbr>Josh.</abbr> Bagstock"_

colophon.xhtml
- [ ] _Hui-chang Wang_ needs to be wrapped with `<b epub:type="z3998:personal-name">`.

content.opf
- [ ] You have a typo in `<dc:subject id="subject-1">`: _Loondon_
- [ ] `<meta property="role" refines="#author" scheme="marc:relators">wpr</meta>` needs to be changed to `<meta property="se:role" refines="#author" scheme="marc:relators">wpr</meta>`. The build system only wants one `property="role"` per creator.

"[Editorial] Modernize hyphenation and spelling" commit
- [ ] chapter-10.xhtml: You changed "Fle-e-eg" to "Flee-eg". When I read it, the word doesn't seem like it should have been changed since it's spelled oddly for comedic purposes.
- [ ] chapter-14.xhtml: "for they everyone looked in" was originally correct with "for they every one looked in"

"Semanticate update" commit
- [ ] chapter-59.xhtml: "a hun-dred thou-sand pound!" was changed to "a hundred thousand pound!" Again, I'm not sure if that's correct since it was spelled properly just a few sentences prior. I believe the hyphens are there to mimic a style of speaking. However, if this is correct and the dashes should be removed, you will need to rebase this commit to include an "[Editorial]" tag.

Editorial changes
- [ ] It looks like both the "Add titles" and the "Proofread chapters" commits include a _lot_ of editorial changes mixed in with non-editorial changes. You will need to do a rebase and move those changes into their own properly tagged commits ([SEMOS 1.4.2](https://standardebooks.org/manual/1.6.4/8-typography#1.4.2)). Any time you changed the spelling on a word by adding or removing a dash or letter, that's something that needs to be tagged separately.

**Comment by alphgal** [comment]
Hi Jason

Thanks for your very thorough check!

I’ve updated all the issues you mentioned except where I've noted it against your original email (see below).

Also, I’m afraid I’m not going to be able to redo the tagging of the commits. I recognise that, as noted in the instructions, “purists” will be horrified that I have not been very good with tagging my commits. However, I have completed a few books now and have definitely made the same tagging mistakes in those previous books and no one picked me up on them before.

I am now much more aware of what I should have done and promise to do better on my next projects, but I believe that me going back and trying to fix what has already been done would not only be very, very time-consuming, but also would be “busy work”. It does nothing to improve the quality of the final product and would be a waste of hours of my time, especially since it is highly unlikely that anyone would want to revisit the work and look for these issues. I’m sure the team would be much keener for me to devote those extra hours to producing another book rather than spending them on this minutiae!

I’m sorry about this - I do take the issue seriously and will definitely work to improve my tagging next time.

Thanks for all your work on this project.

Cheers, Lan

------------------------
Hui-chang (Lan) Wang
***@***.*** ***@***.***>



> On 17 May 2022, at 6:28 am, Jason DeCock ***@***.***> wrote:
> 
> 
> se modernize-spelling (remember to include an [Editorial] tag on the commit)
> 
>  "a-waiting" should be changed to "awaiting" (chapter-44.xhtml)
>  "by the bye" should be changed to "by the by" (chapter-31.xhtml, chapter-32.xhtml, chapter-48.xhtml)
>  "de-vilish" should be changed to "devilish" (chapter-7.xhtml, chapter-10.xhtml, chapter-20.xhtml, chapter-21.xhtml, chapter-26.xhtml, chapter-40.xhtml)
>  "intrust" should be changed to "entrust" (chapter-49.xhtml)
>  "shew" should be changed to "show" (chapter-12.xhtml)
I’ve only changed “intrust”. “By the bye” is acceptable in Websters. All the others are part of the way the characters spoke.

> se find-mismatched-dashes (remember to include an [Editorial] tag on the commit)
> 
>  "cat-like" should be changed to "catlike" (chapter-17.xhtml, chapter-46.xhtml)
> Chapter titles
> 
>  You don't need to keep the chapter label in your chapter titles (SEMOS 8.1.4 <https://standardebooks.org/manual/1.6.4/8-typography#8.1.4>). For example, the Chapter 1 title should be changed to:
> <header>
> 	<h2 epub:type="ordinal z3998:roman">I</h2>
> 	<p epub:type="bridgehead">Dombey and Son.</p>
> </header>
Updated <title> and the ToC as well.

> dedication.xhtml
> 
>  Remove role="doc-dedication"
> preface-1.xhtml and preface-2.xhtml
> 
>  These aren't letters and shouldn't be styled as such. Remove the <blockquote> and epub:type="se:letter.dateline". You'll also need to change [epub|type~="z3998:letter"] footer to footer in local.css.
>  The <time> tag isn't properly formatted. datetime has to be exactly 10 characters long: yyyy-mm-dd.
> chapter-7.xhtml
> 
>  You need to add class="eoc" to <abbr> tags when the final period in it also ends the sentence (SEMOS 8.10.3 <https://standardebooks.org/manual/1.6.4/8-typography#8.10.3>). He’s tough, ma’am, tough, is J. B. Tough, and de-vilish sly!
> chapter-11.xhtml
> 
>  There's a period that needs to be moved inside quotation marks: My opinion is ‘keep ’em at it’.” to My opinion is ‘keep ’em at it.’<HAIR_SPACE>”
> chapter-14.xhtml
> 
>  The <blockquote> should be epub:type="z3998:verse" because it's a poem fragment (SEMOS 7.5.6.1.2 <https://standardebooks.org/manual/1.6.4/8-typography#7.5.6.1.2>).
> chapter-15.xhtml
> 
>  The <blockquote> should be epub:type="z3998:song" (SEMOS 7.5.6.1.3 <https://standardebooks.org/manual/1.6.4/8-typography#7.5.6.1.3>). Between this change and the one for chapter-14.xhtml, you will also need to remove the [epub|type~="z3998:poem"] selectors in local.css and add the selectors for [epub|type~="z3998:verse"] and [epub|type~="z3998:song"].
> chapter-26.xhtml
> 
>  Josh isn't an abbreviation: "Josh. Bagstock"
In this context, “Josh.” is an abbreviation. The character is explaining all the ways in which his name is abbreviated.

> colophon.xhtml
> 
>  Hui-chang Wang needs to be wrapped with <b epub:type="z3998:personal-name">.
> content.opf
> 
>  You have a typo in <dc:subject id="subject-1">: Loondon
>  <meta property="role" refines="#author" scheme="marc:relators">wpr</meta> needs to be changed to <meta property="se:role" refines="#author" scheme="marc:relators">wpr</meta>. The build system only wants one property="role" per creator.
> "[Editorial] Modernize hyphenation and spelling" commit
> 
>  chapter-10.xhtml: You changed "Fle-e-eg" to "Flee-eg". When I read it, the word doesn't seem like it should have been changed since it's spelled oddly for comedic purposes.
>  chapter-14.xhtml: "for they everyone looked in" was originally correct with "for they every one looked in"
> "Semanticate update" commit
> 
>  chapter-59.xhtml: "a hun-dred thou-sand pound!" was changed to "a hundred thousand pound!" Again, I'm not sure if that's correct since it was spelled properly just a few sentences prior. I believe the hyphens are there to mimic a style of speaking. However, if this is correct and the dashes should be removed, you will need to rebase this commit to include an "[Editorial]" tag.
> Editorial changes
> 
>  It looks like both the "Add titles" and the "Proofread chapters" commits include a lot of editorial changes mixed in with non-editorial changes. You will need to do a rebase and move those changes into their own properly tagged commits (SEMOS 1.4.2 <https://standardebooks.org/manual/1.6.4/8-typography#1.4.2>). Any time you changed the spelling on a word by adding or removing a dash or letter, that's something that needs to be tagged separately.

See above

**Comment by jdecock** [comment]
> [Editorial] commits

I understand your feeling about the end product being the same regardless of whether the changes are in a separate commit, but it's a step that they take pretty seriously. I don't think this is negotiable, but I'll get Alex to weigh in here.

I'll comment on the other issues as well, but I kind of doubt they make much difference if doing the the rebase is out of the question.

> I’ve only changed “intrust”. “By the bye” is acceptable in Websters. All the others are part of the way the characters spoke

You're the one who actually read the book, so I'm more than willing to be wrong, but "shew" definitely seems like it should be updated. As far as "by-the-bye" goes, my guess is that it should be updated for consistency, but I'll defer to Alex on it.

> In this context, “Josh.” is an abbreviation. The character is explaining all the ways in which his name is abbreviated.

True that it's an abbreviation, but it's like saying "My name is William but I go by Will for short." You wouldn't typically add a period after it.

**Comment by acabal** [comment]
modernize-spelling should change by the by and shew automatically, you should accept any change it makes unless it's obviously a wrong change in context.

We do need editorial changes in [Editorial] commits. This is an important part of the repo's history, which itself is an important part of the ebook. It's important for reviewers, who will confirm that changes made were correct, and it's important for readers too, to have an easy avenue to see how we've updated the source text. Keeping those kinds of commits separate and demarcated is important.

**Comment by alphgal** [comment]
Hi Alex and Jason

Thanks for your responses. I appreciate the need to keep up standards.

I have just started a long-ish vacation today so I can’t turn my attention to this until I return (in July). 

In the meantime, while I understand in principle what you’d like me to do, I actually don’t know how to go about it at all. I would need to get step by step instructions from someone. As you probably realise, I’m barely literate when it comes to using GitHub …

Cheers, Lan 

-----------------------
Hui-chang (Lan) Wang
***@***.***

**Comment by jdecock** [comment]
I found this video and part 2 very useful when I was learning how to do rebase: https://www.youtube.com/watch?v=e26Zx9K3cdQ

**Comment by alphgal** [comment]
Thanks Jason. That’s very helpful. 

Cheers, Lan 

-----------------------
Hui-chang (Lan) Wang
***@***.***

**Comment by alphgal** [comment]
Hi Jason and Alex

I've had a think about the work that remains to be done on this book and have decided not to go ahead. I'm just too busy to tackle it, especially since I'm in two minds about how useful completing the task would be to the final product.

So, I'm sorry to abandon this project here, but hopefully someone else will be able to pick it up and finish it. I'm more than happy for you to use what I've done so far. All the files will remain on my Github repo.

Good luck with it and the whole Standard Ebooks project. You and the rest of the team are doing a great job.

Thanks
Cheers, Lan

**Comment by acabal** [comment]
OK. Typically we don't continue on work on abandoned ebooks because it's impossible to say what state the repo is in. You can delete it from your Github account if you like.
